FROM python:3.11-slim-bullseye as base

ENV PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.3

WORKDIR /app

#RUN apk add --no-cache gcc musl-dev libpq-dev wget
RUN apt-get update && apt-get install -y wget bzip2
# install dhall-json
RUN wget https://github.com/dhall-lang/dhall-haskell/releases/download/1.41.2/dhall-json-1.7.11-x86_64-Linux.tar.bz2
RUN tar --extract --file dhall-json-*-x86_64-Linux.tar.bz2

RUN pip install --no-cache "poetry==$POETRY_VERSION"
RUN python -m venv /venv

COPY pyproject.toml poetry.lock ./
RUN poetry export -f requirements.txt | /venv/bin/pip install -r /dev/stdin

FROM base as final

RUN mkdir build -p

COPY core/validate.py validate.py
COPY configs configs
COPY media media

CMD /app/bin/dhall-to-json --file configs/servers.dhall --output build/config.json && \
    /venv/bin/python validate.py
